name: Infrastructure deploy
on:
  workflow_dispatch:
    inputs:
      aws-environment:
        required: true
        type: choice
        options: [ lab, dev, qa, ppe, prod ]
      aws-region:
        required: true
        type: choice
        options: [ us-east-1, eu-west-1 ]
env:
  ASSET_ID: a123456
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'setup'
  frame-0:
    needs: setup
    uses: ./.github/workflows/infra-deploy-stack.yml
    with:
      working-directory: '["./infrastructure/manifest/app-name/global/global-module-1"]'
      github-environment: protected-lab
      aws-environment: ${{ inputs.aws-environment }}
      aws-region: ${{ inputs.aws-region }}
      aws-assume-role: generated-aws-role-arn
      asset-id: a123456
    secrets: inherit
