name: Infrastructure deploy
on:
  workflow_dispatch:
    inputs:
      aws-environment:
        required: true
        type: choice
        options: [ lab, dev, qa, ppe, prod ]
      aws-region:
        required: true
        type: choice
        options: [ us-east-1, eu-west-1 ]
env:
  ASSET_ID: a123456
  INFRA_PATH: ./infrastructure/manifest/app-name
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      stacksGroups: ${{ steps.setup.outputs.stacksGroups }}
    steps:
      - id: setup
        shell: pwsh
        working-directory: ${{ env.INFRA_PATH }}
        run: |
          $Groups = @{}

          Get-ChildItem -Filter "gh-deployment.properties" -Recurse | ForEach-Object { 
              $Properties = Get-Content $_.FullName -Raw | ConvertFrom-StringData

              $GroupId = $Properties['group-id']

              if (!$Groups.ContainsKey($GroupId))
              {
                  $Groups.Add($GroupId, @()) | Out-Null
              }

              $Groups[$GroupId] += $_.Directory.FullName
          }
          
          echo "stacksGroups=$($Groups | ConvertTo-Json -Compress)" >> $Env:GITHUB_OUTPUT

  group-0:
    needs: setup
    steps:
      - run: echo '${{ needs.setup.outputs.stacksGroups }}'
