name: Infrastructure deploy
on:
  workflow_dispatch:
    inputs:
      aws-environment:
        required: true
        type: choice
        options: [ lab, dev, qa, ppe, prod ]
      aws-region:
        required: true
        type: choice
        options: [ us-east-1, eu-west-1 ]
env:
  ASSET_ID: a123456
  INFRA_PATH: ./infrastructure/manifest/app-name
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      stacksGroups: ${{ steps.setup.outputs.stacksGroups }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup
        working-directory: ${{ env.INFRA_PATH }}
        shell: pwsh
        run: |
          $Groups = @{}

          Get-ChildItem -Filter "gh-deployment.properties" -Recurse | ForEach-Object { 
              $Properties = Get-Content $_.FullName -Raw | ConvertFrom-StringData

              $GroupId = $Properties['group-id']

              if (!$Groups.ContainsKey($GroupId))
              {
                  $Groups.Add($GroupId, @()) | Out-Null
              }

              $Groups[$GroupId] += $_.Directory.FullName
          }
          
          echo "stacksGroups=$($Groups | ConvertTo-Json -Compress)" >> $Env:GITHUB_OUTPUT

  group-0:
    needs: setup
    uses: ./.github/workflows/print.yml
    strategy:
      matrix:
        path: ${{ fromJson(needs.setup.outputs.stacksGroups)['group-0'] }}
    with:
      path: ${{ matrix.path }}
  group-1:
    needs: [setup, group-0]
    uses: ./.github/workflows/print.yml
    strategy:
      matrix:
        path: ${{ fromJson(needs.setup.outputs.stacksGroups)['group-1'] }}
    with:
      path: ${{ matrix.path }}
