name: Infrastructure deploy
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'setup'
  frame-0:
    needs: setup
    uses: ./.github/workflows/infra-deploy-stack.yml
    with:
      working-directory: '["A", "B"]'
      github-environment: protected-lab
      aws-region: us-east-1
      aws-assume-role: generated-aws-role-arn
    secrets: inherit
