name: Deploy infrastructure stack
on:
  workflow_call:
    inputs:
      working-directory:
        type: string # json-array
        required: true
      github-environment:
        type: string
        required: true
jobs:
  plan:
    strategy:
      matrix:
        working-directory: ${{ fromJson(inputs.working-directory) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'plan ${{ matrix.working-directory }}'
  apply:
    needs: plan
    environment: ${{ inputs.github-environment }}
    strategy:
      matrix:
        working-directory: ${{ fromJson(inputs.working-directory) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'apply ${{ matrix.working-directory }}'
